/**
 * LLM Integration Types
 * 
 * Purpose: Type definitions for LLM API responses (Gemini + Groq)
 * DO NOT implement actual integration until Plan 04 (Pivot Generation)
 */

/**
 * LLM provider configuration
 */
export type LLMProvider = 'gemini' | 'groq';

/**
 * LLM request parameters
 */
export interface LLMRequest {
  prompt: string;
  provider: LLMProvider;
  temperature?: number;
  maxTokens?: number;
  // TODO: Add streaming support
}

/**
 * LLM response structure
 */
export interface LLMResponse {
  content: string;
  provider: LLMProvider;
  tokensUsed?: number;
  cached?: boolean;
}

/**
 * Career pivot path generated by LLM
 */
export interface PivotPath {
  title: string;
  description: string;
  timeline: string; // "90 days"
  skillGaps: SkillGap[];
  // TODO: Add milestones, resources, validation steps
}

/**
 * Skill gap analysis
 */
export interface SkillGap {
  skill: string;
  currentLevel: 'none' | 'beginner' | 'intermediate' | 'advanced';
  targetLevel: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedTime: string; // e.g., "20 hours"
  resources: Resource[];
}

/**
 * Learning resource
 */
export interface Resource {
  title: string;
  url: string;
  type: 'course' | 'tutorial' | 'documentation' | 'book';
  estimatedTime?: string;
}

// TODO (Plan 04): Add rate limiting types
// TODO (Plan 04): Add queue types for fallback strategy
