/**
 * LLM Integration Types
 * 
 * Purpose: Type definitions for LLM API responses (Gemini + Groq)
 */

/**
 * LLM provider configuration
 */
export type LLMProvider = 'gemini' | 'groq';

/**
 * LLM response structure
 */
export interface LLMResponse {
  content: string;
  provider: 'gemini' | 'groq';
  model: string;
  tokensUsed?: number;
  latencyMs: number;
}

/**
 * LLM error structure
 */
export interface LLMError {
  provider: 'gemini' | 'groq';
  error: string;
  code?: string;
  retryable: boolean;
}

/**
 * Narrative generation request
 */
export interface NarrativeRequest {
  pivotPath: {
    currentRole: string;
    targetRole: string;
    skillGaps: string[];
    transferableSkills: string[];
    fitScore: number;
  };
  userContext: {
    yearsExperience: number;
    timeAvailable: number; // hours per week
    constraints?: string[];
  };
}

/**
 * Career pivot path generated by LLM
 */
export interface PivotPath {
  title: string;
  description: string;
  timeline: string; // "90 days"
  skillGaps: SkillGap[];
  // TODO: Add milestones, resources, validation steps
}

/**
 * Skill gap analysis
 */
export interface SkillGap {
  skill: string;
  currentLevel: 'none' | 'beginner' | 'intermediate' | 'advanced';
  targetLevel: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedTime: string; // e.g., "20 hours"
  resources: Resource[];
}

/**
 * Learning resource
 */
export interface Resource {
  title: string;
  url: string;
  type: 'course' | 'tutorial' | 'documentation' | 'book';
  estimatedTime?: string;
}
